all:
  hosts:
    vm_azure:
      ansible_host: "{{ lookup('pipe', 'cd .. && terraform output -raw public_ip_address') }}"
      ansible_user: azureuser
      ansible_become: yes
      ansible_become_method: sudo
